module Redis
  # Commands in this set are routed to replicas by `Redis::Cluster` and
  # `Redis::ReplicationClient`.
  #
  # You can add additional commands that this shard does not yet know about
  # (for example, one provided by a custom Redis module) by using the `<<` method:
  #
  # ```
  # Redis::READ_ONLY_COMMANDS << "mymodule.mycommand"
  # ```
  READ_ONLY_COMMANDS = %w[
    bf.card
    bf.debug
    bf.exists
    bf.info
    bf.mexists
    bf.scandump
    bitcount
    bitfield_ro
    bitpos
    cf.compact
    cf.count
    cf.debug
    cf.exists
    cf.info
    cf.mexists
    cf.scandump
    cms.info
    cms.query
    dbsize
    dump
    eval_ro
    evalsha_ro
    exists
    expiretime
    fcall_ro
    ft._aliasaddifnx
    ft._aliasdelifx
    ft._list
    ft.aggregate
    ft.aliasadd
    ft.aliasdel
    ft.aliasupdate
    ft.config
    ft.cursor
    ft.debug
    ft.dictadd
    ft.dictdel
    ft.dictdump
    ft.explain
    ft.explaincli
    ft.get
    ft.info
    ft.mget
    ft.profile
    ft.search
    ft.spellcheck
    ft.sugget
    ft.suglen
    ft.syndump
    ft.tagvals
    geodist
    geohash
    geopos
    georadius_ro
    georadiusbymember_ro
    geosearch
    get
    getbit
    getrange
    hexists
    hget
    hgetall
    hkeys
    hlen
    hmget
    hrandfield
    hscan
    hstrlen
    hvals
    json.arrindex
    json.arrlen
    json.debug
    json.get
    json.mget
    json.objkeys
    json.objlen
    json.resp
    json.strlen
    json.type
    keys
    lcs
    lindex
    llen
    lolwut
    lpos
    lrange
    mget
    pexpiretime
    pfcount
    pttl
    randomkey
    redisgears_2.clusterset
    redisgears_2.clustersetfromshard
    redisgears_2.forceshardsconnection
    redisgears_2.hello
    redisgears_2.infocluster
    redisgears_2.innercommunication
    redisgears_2.networktest
    redisgears_2.refreshcluster
    scan
    scard
    sdiff
    sinter
    sintercard
    sismember
    smembers
    smismember
    sort_ro
    srandmember
    sscan
    strlen
    substr
    sunion
    tdigest.byrank
    tdigest.byrevrank
    tdigest.cdf
    tdigest.info
    tdigest.max
    tdigest.min
    tdigest.quantile
    tdigest.rank
    tdigest.revrank
    tdigest.trimmed_mean
    timeseries.clusterset
    timeseries.clustersetfromshard
    timeseries.forceshardsconnection
    timeseries.hello
    timeseries.infocluster
    timeseries.innercommunication
    timeseries.networktest
    timeseries.refreshcluster
    topk.info
    topk.list
    topk.query
    touch
    ts.get
    ts.info
    ts.mget
    ts.mrange
    ts.mrevrange
    ts.queryindex
    ts.range
    ts.revrange
    ttl
    type
    xlen
    xpending
    xrange
    xread
    xrevrange
    zcard
    zcount
    zdiff
    zinter
    zintercard
    zlexcount
    zmscore
    zrandmember
    zrange
    zrangebylex
    zrangebyscore
    zrank
    zrevrange
    zrevrangebylex
    zrevrangebyscore
    zrevrank
    zscan
    zscore
    zunion
  ].to_set
end
