name: Crystal CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Docker Run Action
      uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185
      with:
        image: redis/redis-stack-server
        options: --detach -p 6379:6379
        run: redis-stack-server
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
