name: Crystal CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    services:
      redis:
        image: redis/redis-stack-server
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
      env:
        REDIS_URL: redis://redis/
